import type { Product } from "../../data/product";

export const ShopProductData: Product[] = [
  {
    id: 1,
    title: "Freestyle Crew Racer Leather Jacket",
    price: 595.0,
    image: "/Best Sellers/Paste image.svg",
    desc: "Crafted from premium leather, this racer jacket offers a sleek silhouette with a rugged edge — perfect for urban explorers and classic style lovers.",
    discountedPrice: 416.0,
    isNew: true,
    discount: 20,
  },
  {
    id: 2,
    title: "1996 Retro Nuptse Cashmere Jacket in Gray",
    price: 149.99,
    image: "/Best Sellers/2.svg",
    desc: "A timeless puffer reinvented in soft cashmere-blend fabric, delivering unmatched warmth and vintage-inspired style for winter outings.",
    isNew: true,
  },
  {
    id: 3,
    title: "Chilliwack Black Bomber HUMANATUR",
    price: 1195.99,
    image: "/Best Sellers/3.svg",
    desc: "This bomber blends heritage flight design with functional warmth, tailored for cold weather with a bold, street-ready aesthetic.",
    isNew: true,
  },
  {
    id: 4,
    title: "96 Nuptse Dip Dye Bomber Jacket",
    price: 400.99,
    image: "/Best Sellers/4.svg",
    desc: "Featuring a striking dip-dye finish, this retro-styled bomber combines iconic Nuptse insulation with bold modern coloring.",
    isNew: true,
  },
  {
    id: 5,
    title: "Oversized Real Leather Harrington Jacket in Black",
    price: 249.99,
    image: "/Best Sellers/5.svg",
    desc: "A fashion-forward take on the classic Harrington, crafted in real leather with an oversized fit for ultimate cool and comfort.",
    isNew: true,
  },
  {
    id: 6,
    title: "Men's Diamond Quilted Bomber Hoody",
    price: 199.95,
    image: "/Best Sellers/6.svg",
    desc: "This hybrid bomber-hoodie features diamond quilting for added warmth and style — ideal for layering through the seasons.",
    isNew: true,
  },
  {
    id: 7,
    title: "Paradigm Chilliwack Coat Black Label",
    price: 1495,
    image: "/Best Sellers/7.svg",
    desc: "Luxury meets function in this down-filled coat, made for extreme conditions with premium materials and a tailored silhouette.",
    isNew: true,
  },
  {
    id: 8,
    title: "Men's Torrentshell 3L Rain Jacket in Brown",
    price: 149.0,
    image: "/Best Sellers/8.svg",
    desc: "Stay dry and mobile with this lightweight, 3-layer rain jacket. Durable, packable, and perfect for unpredictable weather.",
    isNew: true,
  },
];
